In [10]:
import cv2
import numpy as np
import matplotlib as plt

Convert image to grayscale

In [19]:
img_gray=cv2.imread("Coin.png",0)
window_name = 'Grayscale image'
cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
cv2.imshow(window_name,img_gray)
cv2.waitKey(0)

48

perform convolution kernel

In [20]:
img_arr = np.array(img_gray)
print(img_gray)

[[255 255 255 ... 255 255 255]
 [232 231 230 ... 234 234 235]
 [231 231 231 ... 236 236 236]
 ...
 [198 198 198 ... 180 181 183]
 [197 197 197 ... 181 184 184]
 [197 198 199 ... 184 186 187]]


In [21]:
def convolve2D(image, kernel, padding=0, strides=1):
    # Cross Correlation
    kernel = np.flipud(np.fliplr(kernel))

    # Gather Shapes of Kernel + Image + Padding
    xKernShape = kernel.shape[0]
    yKernShape = kernel.shape[1]
    xImgShape = image.shape[0]
    yImgShape = image.shape[1]

    # Shape of Output Convolution
    xOutput = int(((xImgShape - xKernShape + 2 * padding) / strides) + 1)
    yOutput = int(((yImgShape - yKernShape + 2 * padding) / strides) + 1)
    output = np.zeros((xOutput, yOutput))

    # Apply Equal Padding to All Sides
    if padding != 0:
        imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
        imagePadded[int(padding):int(-1 * padding), int(padding):int(-1 * padding)] = image
        print(imagePadded)
    else:
        imagePadded = image

    # Iterate through image
    for y in range(image.shape[1]):
        # Exit Convolution
        if y > image.shape[1] - yKernShape:
            break
        # Only Convolve if y has gone down by the specified Strides
        if y % strides == 0:
            for x in range(image.shape[0]):
                # Go to next row once kernel is out of bounds
                if x > image.shape[0] - xKernShape:
                    break
                try:
                    # Only Convolve if x has moved by the specified Strides
                    if x % strides == 0:
                        output[x, y] = (kernel * imagePadded[x: x + xKernShape, y: y + yKernShape]).sum()
                except:
                    break

    return output

In [42]:
avgKernel = np.array([[1/16, 2/16, 1/16], [4/16, 2/16, 4/16], [1/16, 2/16, 1/16]])
xKernel = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
yKernel = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])

img_grey = convolve2D(img_gray, avgKernel)

xImg = np.uint8(np.absolute(convolve2D(img_grey, xKernel)))
cv2.imshow('x', xImg)
cv2.waitKey(0)

yImg = np.uint8(np.absolute(convolve2D(img_grey, yKernel)))
cv2.imshow('y', yImg)
cv2.waitKey(0)

combinedImg = cv2.bitwise_or(xImg, yImg)
cv2.imshow('combined', combinedImg)
cv2.waitKey(0)

48

Canny

In [43]:
image = cv2.imread("Coin.png", 0)

In [45]:
image_blur = cv2.GaussianBlur(image, (5, 5), 0)
image_canny = cv2.Canny(image_blur, 100, 200)
contour, hierarchy = cv2.findContours(image_canny, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(image, contour, -1, (255, 0, 0), 2)

ValueError: too many values to unpack (expected 2)

In [ ]:
cv2.imshow("Blurred", image_blur)
cv2.imshow("Canny", image_canny)
cv2.imshow("contoured", image)
cv2.waitKey(0)